apiVersion: apps/v1
kind: Deployment
metadata:
  name: doleo-client-production
  namespace: doleo
  labels:
    app: doleo-client-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doleo-client-production
  template:
    metadata:
      labels:
        app: doleo-client-production
    spec:
      containers:
      - name: doleo-client-production
        image: spuxx/doleo-2-client:main-20241016-070939-512f0dea5b7c940ee0dd4a0deb5a0d5c9303648c
        ports:
        - containerPort: 8080
        securityContext:
          runAsNonRoot: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
