---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
        - name: home-assistant
          image: "ghcr.io/home-assistant/home-assistant:2024.7.0.dev202406160221"
          ports:
            - containerPort: 8123
          securityContext:
            runAsUser: 9001
            runAsGroup: 8001
            fsGroup: 8001
          volumeMounts:
            - name: config
              mountPath: /config
          env:
            - nam: TZ
              value: "Europe/Berlin"
            - name: PUID
              value: "9001"
            - name: PGID:
              value: "8001"
            - name: UMASK
              value: "7001"
            - name: PACKAGES
              value: iputils
      volumes:
        - name: config
          hostPath:
            path: /home/homeassistant/homeassistant-config