---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  namespace: home-assistant
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: hub.fritz.box
      http:
        paths:
          - path: /home-assistant(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: home-assistant
                port:
                  number: 8080
