---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly
  namespace: spuxx-dev
  labels:
    app: firefly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firefly
  template:
    metadata:
      labels:
        app: firefly
    spec:
      containers:
        - name: firefly
          image: fireflyiii/core:latest
          ports:
            - containerPort: 8080
          # securityContext:
          #   runAsUser: 9004
          #   allowPrivilegeEscalation: true
          #   capabilities:
          #     add:
          #       - CHOWN
          #       - CHMOD
          volumeMounts:
            - name: uploads
              mountPath: /var/www/html/storage/upload
          env:
            - name: DB_HOST
              value: mariadb.storage.svc.cluster.local
            - name: DB_CONNECTION
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: firefly
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: firefly
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: firefly
                  key: DB_PASSWORD
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: firefly
                  key: APP_KEY
      volumes:
        - name: uploads
          hostPath:
            path: /home/firefly/uploads
