apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-secrets
  namespace: flux-system
spec:
  interval: 5m
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/spuxx-dev/kube.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-secrets
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/constellation/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-secrets
  decryption:
    provider: sops
    secretRef:
      name: sops-age
