version: 2
updates:
- package-ecosystem: "docker"
  directory: "/clusters/constellation/**"
  schedule:
    interval: "daily"
- package-ecosystem: "docker"
  directory: "/clusters/home/**"
  schedule:
    interval: "daily"
