version: 2
updates:
- package-ecosystem: "docker"
  directory: "/clusters/constellation/storage/mariadb"
  schedule:
    interval: "daily"
- package-ecosystem: "docker"
  directory: "/clusters/constellation/apps/actualbudget"
  schedule:
    interval: "daily"
- package-ecosystem: "docker"
  directory: "/clusters/constellation/apps/adminer"
  schedule:
    interval: "daily"
- package-ecosystem: "docker"
  directory: "/clusters/constellation/apps/audiobookshelf"
  schedule:
    interval: "daily"
