---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloakwp
          image: keycloak/keycloak:25.0.2
          ports:
            - name: http
              containerPort: 8080
            - name: health
              containerPort: 9000
          securityContext:
            runAsUser: 9999
          args:
            - "start"
          env:
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: KC_DB_USERNAME
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: KC_DB_PASSWORD
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: KEYCLOAK_ADMIN_PASSWORD
          envFrom:
            - configMapRef:
                name: keycloak
          livenessProbe:
            httpGet:
              path: /health/live
              port: health
          readinessProbe:
            httpGet:
              path: /health/ready
              port: health
