apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-horizons-client-staging
  namespace: new-horizons
  labels:
    app: new-horizons-client-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new-horizons-client-staging
  template:
    metadata:
      labels:
        app: new-horizons-client-staging
    spec:
      containers:
        - name: new-horizons-client-staging
          image: spuxx/new-horizons-client:main-20230708-092528-3b16beb5d7f31772beb822645eea1144b7aaaf3c # {"$imagepolicy": "new-horizons:new-horizons-client-staging"}
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
