---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: potber-auth-production
  namespace: potber
spec:
  imageRepositoryRef:
    name: potber-auth
  policy:
    semver:
      range: "^2.x-0"
