---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-apps
  namespace: flux-system
spec:
  interval: 3m
  path: ./clusters/jupiter/apps/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system