apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie
  namespace: mealie
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-storage
  resources:
    requests:
      storage: 5Gi
