apiVersion: apps/v1
kind: Deployment
metadata:
  name: potber-api-staging
  namespace: potber
  labels:
    app: potber-api-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: potber-api-staging
  template:
    metadata:
      labels:
        app: potber-api-staging
    spec:
      containers:
        - name: potber-api-staging
          image: spuxx/potber-api:main-20231026-170450-6c4eb6a06c15a068d9a9dc77ca2f30ec6ff27a75 # {"$imagepolicy": "potber:potber-api-staging"}
          env:
            - name: APP_PORT
              value: "3000"
            - name: APP_CLIENT_URL
              value: https://test.potber.de
            - name: APP_API_URL
              value: https://test-api.potber.de
            - name: SWAGGER_TEST_THREAD_ID
              value: "219289"
            - name: CORS_ALLOWED_ORIGINS
              value: https://test.potber.de
            - name: AUTH_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: potber-api
                  key: AUTH_JWT_SECRET
          ports:
            - containerPort: 3000
          securityContext:
            runAsNonRoot: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
