apiVersion: apps/v1
kind: Deployment
metadata:
  name: potber-api-staging
  namespace: potber
  labels:
    app: potber-api-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: potber-api-staging
  template:
    metadata:
      labels:
        app: potber-api-staging
    spec:
      containers:
        - name: potber-api-staging
          image: spuxx/potber-api:master-20230516-105049-c15163c25959115f7473e8e8e9faaf33d71d5d86 # {"$imagepolicy": "potber:potber-api-staging"}
          env:
            - name: APP_PORT
              value: "3000"
            - name: APP_CLIENT_URL
              value: https://potber-test.spuxx.dev
            - name: APP_API_URL
              value: https://potber-api-test.spuxx.dev
            - name: SWAGGER_TEST_THREAD_ID
              value: "219289"
            - name: CORS_ALLOWED_ORIGINS
              value: https://potber-test.spuxx.dev
            - name: AUTH_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: potber-api
                  key: AUTH_JWT_SECRET
          ports:
            - containerPort: 3000
          securityContext:
            runAsNonRoot: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
