---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: potber-api-staging
  namespace: potber
spec:
  imageRepositoryRef:
    name: potber-api
  filterTags:
    pattern: 'master*'
  policy:
    alphabetical:
      order: asc