---
apiVersion: v1
kind: Service
metadata:
  name: potber-api-staging
  namespace: potber
  labels:
    monitoringGroup: potber-api
spec:
  selector:
    app: potber-api-staging
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: metrics
      protocol: TCP
      port: 9100
      targetPort: 9100
