---
# Docs: https://github.com/spuxx1701/docker-ark
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - persistent-volume-claim.yaml
  - config-map.yaml
  # - deployment.yaml
