---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-se
  namespace: game-servers
spec:
  storageClassName: host-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
