apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ui
  namespace: longhorn-system
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/longhorn)$ $1/ redirect;
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-url: "https://constellation.spuxx.dev/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://constellation.spuxx.dev/oauth2/start?rd=$escaped_request_uri"
spec:
  tls:
  - hosts:
    - "*.spuxx.dev"
    secretName: spuxx.dev
  rules:
  - host: constellation.spuxx.dev
    http:
      paths:
      - path: /longhorn(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
