---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: potber.de
  namespace: potber
spec:
  secretName: potber.de
  duration: 2160h # 90d
  renewBefore: "528h" # renew 22 days before to avoid LE email warning
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
    rotationPolicy: Always
  usages:
    - server auth
    - client auth
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.potber.de"
  dnsNames:
    - "potber.de"
    - "*.potber.de"
