---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: potber-client-staging
  namespace: potber
spec:
  imageRepositoryRef:
    name: potber-client
  filterTags:
    pattern: 'main*'
  policy:
    alphabetical:
      order: asc