---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-dynamic
  namespace: paperless-ngx
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-storage
  resources:
    requests:
      storage: 10Gi
