apiVersion: apps/v1
kind: Deployment
metadata:
  name: potber-client-staging
  namespace: potber
  labels:
    app: potber-client-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: potber-client-staging
  template:
    metadata:
      labels:
        app: potber-client-staging
    spec:
      containers:
        - name: potber-client-staging
          image: spuxx/potber-client:main-20231107-122233-777fab6f327fa6abf0b3df9c3257514b802e0b6c # {"$imagepolicy": "potber:potber-client-staging"}
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
