---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  namespace: monitoring
spec:
  storageClassName: ""
  volumeName: monitoring
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
