apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-dynamic
  namespace: audiobookshelf
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-storage
  resources:
    requests:
      storage: 50Gi
---


