apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-static
  namespace: audiobookshelf
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-storage
  resources:
    requests:
      storage: 30Gi
---

