---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: potber-api-production
  namespace: potber
spec:
  imageRepositoryRef:
    name: potber-api
  policy:
    semver:
      range: '^2.x-0'
