---
apiVersion: v1
kind: Service
metadata:
  name: potber-api-production
  namespace: potber
spec:
  selector:
    app: potber-api-production
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
