---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: spuxx-dev
  labels:
    app: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer:4.8.1
          ports:
            - containerPort: 8080
          securityContext:
            runAsUser: 9001
          env:
            - name: ADMINER_DEFAULT_SERVER
              value: mariadb.storage.svc.cluster.local
