---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actualbudget
  namespace: spuxx-dev
  labels:
    app: actualbudget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actualbudget
  template:
    metadata:
      labels:
        app: actualbudget
    spec:
      containers:
        - name: actualbudget
          image: actualbudget/actual-server:latest
          ports:
            - containerPort: 8080
          securityContext:
            runAsUser: 9004
          volumeMounts:
            - name: data
              mountPath: /data
          env:
            - name: ACTUAL_PORT
              value: "8080"
      volumes:
        - name: data
          hostPath:
            path: /home/actualbudget/data
