apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actualbudget
  namespace: actualbudget
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-storage
  resources:
    requests:
      storage: 1Gi
