---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: new-horizons-client-production
  namespace: new-horizons
spec:
  imageRepositoryRef:
    name: new-horizons-client
  policy:
    semver:
      range: '^0.x-0'