apiVersion: apps/v1
kind: Deployment
metadata:
  name: doleo-client-staging
  namespace: doleo
  labels:
    app: doleo-client-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doleo-client-staging
  template:
    metadata:
      labels:
        app: doleo-client-staging
    spec:
      containers:
        - name: doleo-client-staging
          image: spuxx/doleo-2-client:main-20240511-085011-235623c759709b6dc6792f8bbfadb5cf1049513b # {"$imagepolicy": "doleo:doleo-client-staging"}
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
