---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: doleo-client-staging
  namespace: doleo
spec:
  imageRepositoryRef:
    name: doleo-client
  filterTags:
    pattern: "main*"
  policy:
    alphabetical:
      order: asc
