apiVersion: apps/v1
kind: Deployment
metadata:
  name: doleo-backend-production
  namespace: doleo
  labels:
    app: doleo-backend-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doleo-backend-production
  template:
    metadata:
      labels:
        app: doleo-backend-production
    spec:
      containers:
      - name: doleo-backend-production
        image: spuxx/doleo-2-backend # {"$imagepolicy": "doleo:doleo-backend-production"}
        env:
        - name: APP_CLIENT_URL
          value: https://doleo-2.de
        - name: CORS_ALLOWED_ORIGINS
          value: https://doleo-2.de,https://www.doleo-2.de
        - name: DATABASE_HOST
          value: mariadb.database.svc.cluster.local
        - name: DATABASE_PORT
          value: "3306"
        - name: DATABASE_DB
          value: doleo-production
        - name: DATABASE_SYNCHRONIZE
          value: "true"
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: doleo-backend-production
              key: DATABASE_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: doleo-backend-production
              key: DATABASE_PASSWORD
        - name: AUTH_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: doleo-backend-production
              key: AUTH_JWT_SECRET
        - name: VAPID_PUBLIC_KEY
          value: BKK7bl54Trjsx1JE3uvAWs78ADQMKTXxRDMS8nvDt6A1KgEFPUuRG6pUkT53hUrkwYDdgJE2OprRuLW4rG-qfy0
        - name: VAPID_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: doleo-backend-staging
              key: VAPID_PRIVATE_KEY
        ports:
        - containerPort: 3000
        securityContext:
          runAsNonRoot: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
