apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
spec:
  # Mounts the prometheus configmap to the containerl, copies the config to the
  # /etc/prometheus directory and changes the owner to the prometheus user
  initContainers:
    - name: copy-config
      image: busybox
      command:
        [
          "sh",
          "-c",
          "cp /config/prometheus.yml /etc/prometheus/prometheus.yml && chown 9002:9002 /etc/prometheus/prometheus.yml",
        ]
      volumeMounts:
        - name: prometheus-config
          mountPath: /config
        - name: monitoring
          mountPath: /etc/prometheus
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          securityContext:
            runAsUser: 9002
          volumeMounts:
            - name: monitoring
              mountPath: /etc/prometheus
      volumes:
        - name: monitoring
          hostPath:
            path: /home/monitoring/prometheus
        - name: prometheus-config
          configMap:
            name: prometheus-config
