apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: spuxx-api-staging
  namespace: spuxx-dev
spec:
  imageRepositoryRef:
    name: spuxx-api-staging
  policy:
  filterTags:
    pattern: 'main*'
  policy:
    alphabetical:
      order: asc
