apiVersion: apps/v1
kind: Deployment
metadata:
  name: potber-auth-staging
  namespace: potber
  labels:
    app: potber-auth-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: potber-auth-staging
  template:
    metadata:
      labels:
        app: potber-auth-staging
    spec:
      containers:
        - name: potber-auth-staging
          image: spuxx/potber-api:main # {"$imagepolicy": "potber:potber-auth-staging"}
          env:
            - name: API_URL
              value: https://api-test.potber.de
            - name: API_LOGIN_ENDPOINT
              value: /auth/login
            - name: API_SESSION_ENDPOINT
              value: /auth/session
          ports:
            - containerPort: 3000
          securityContext:
            runAsNonRoot: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
