apiVersion: apps/v1
kind: Deployment
metadata:
  name: potber-auth-staging
  namespace: potber
  labels:
    app: potber-auth-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: potber-auth-staging
  template:
    metadata:
      labels:
        app: potber-auth-staging
    spec:
      containers:
        - name: potber-auth-staging
          image: spuxx/potber-auth:main-20240906-172249-e357bce6dd5848efde4052f624e1ffcfcc8f5c1b # {"$imagepolicy": "potber:potber-auth-staging"}
          env:
            - name: VITE_API_URL
              value: https://test-api.potber.de
            - name: VITE_API_LOGIN_ENDPOINT
              value: /auth/login
            - name: VITE_API_SESSION_ENDPOINT
              value: /auth/session
          ports:
            - containerPort: 3000
          securityContext:
            runAsNonRoot: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
