---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: potber-auth-staging
  namespace: potber
spec:
  imageRepositoryRef:
    name: potber-auth
  filterTags:
    pattern: "main*"
  policy:
    alphabetical:
      order: asc
