---
# Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: leopoldhock.de
  namespace: lets-encrypt
spec:
  secretName: leopoldhock.de
  duration: 2160h # 90d
  renewBefore: "528h" # renew 22 days before to avoid LE email warning
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
    rotationPolicy: Always
  usages:
    - server auth
    - client auth
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretTemplate:
    annotations:
      # Tell reflector to reflect the TLS secret into other namespaces. This is required
      # for ingress in other namespaces to use this certificate since secrets cannot be used
      # across namespaces.
      # See https://cert-manager.io/docs/tutorials/syncing-secrets-across-namespaces/#using-reflector
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "spuxx-dev"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "spuxx-dev"
  commonName: "*.leopoldhock.de"
  dnsNames:
    - "leopoldhock.de"
    - "*.leopoldhock.de"
