apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kitchenowl
  namespace: kitchenowl
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-storage-v2
  resources:
    requests:
      storage: 5Gi
