apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kitchenowl
  namespace: kitchenowl
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-storage
  resources:
    requests:
      storage: 5Gi
