---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kitchenowl-static
  namespace: kitchenowl
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-storage
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "2"
      staleReplicaTimeout: "2880"
    volumeHandle: "kitchenowl-backup-1aa5bd69e0f749a9"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kitchenowl-static
  namespace: kitchenowl
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-storage
  volumeName: kitchenowl-static
  resources:
    requests:
      storage: 5Gi
