---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kitchenowl-aa0bbf6a-41ad-4592-be6b-47a5ca5cf223
  namespace: kitchenowl
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-storage
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "2"
      staleReplicaTimeout: "2880"
    volumeHandle: "pvc-aa0bbf6a-41ad-4592-be6b-47a5ca5cf223"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kitchenowl-aa0bbf6a-41ad-4592-be6b-47a5ca5cf223
  namespace: kitchenowl
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-storage
  volumeName: kitchenowl-aa0bbf6a-41ad-4592-be6b-47a5ca5cf223
  resources:
    requests:
      storage: 5Gi
