# See: https://github.com/ory/k8s/blob/master/helm/charts/kratos/values.yaml
service:
  admin:
    enabled: false
  public:
    enabled: false
ingress:
  admin:
    enabled: false
  public:
    enabled: false
kratos:
  automigration:
    enabled: true
    type: initContainer
  serviceAccount:
    create: false
autoscaling:
  enabled: false
courier:
  enabled: false
watcher:
  enabled: false
cleanup:
  enabled: false
pdb:
  enabled: false
serviceMonitor:
  enabled: false
