---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: storage
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:11.4.2
          ports:
            - containerPort: 3306
          securityContext:
            runAsUser: 9001 # mariadb user
          volumeMounts:
            - name: mariadb
              mountPath: /var/lib/mysql
            - name: mariadb-config
              mountPath: /etc/mysql/conf.d
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: MARIADB_ROOT_PASSWORD
      volumes:
        - name: mariadb
          hostPath:
            path: /home/mariadb
        - name: mariadb-config
          configMap:
            name: mariadb-config
