---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  namespace: storage
spec:
  storageClassName: ""
  volumeName: mariadb
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
