apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb
  labels:
    type: local
spec:
  storageClassName: host-storage
  type: hostPath
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: mariadb
    namespace: storage
  capacity:
    storage: 10Gi
