---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb
  namespace: paperless-ngx
data:
  MARIADB_DATABASE: paperless
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: paperless-ngx
data:
  custom.cnf: |
    [mariadb]
    bind-address = 0.0.0.0
