---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: new-horizons-client-staging
  namespace: new-horizons
spec:
  imageRepositoryRef:
    name: new-horizons-client
  filterTags:
    pattern: 'main*'
  policy:
    alphabetical:
      order: asc