apiVersion: apps/v1
kind: Deployment
metadata:
  name: spuxx-dev
  namespace: spuxx-dev
  labels:
    app: spuxx-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spuxx-dev
  template:
    metadata:
      labels:
        app: spuxx-dev
    spec:
      containers:
        - name: spuxx-dev
          image: spuxx/spuxx-dev:master-20230623-113521-ecb1bc0086c5c2b539f61c7edc50429fc3b2a833 # {"$imagepolicy": "spuxx-dev:spuxx-dev"}
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
