apiVersion: v1
kind: ConfigMap
metadata:
  name: potber-client-production
  namespace: potber
data:
  injected-config.js: |
    window.APP = {
      HOSTNAME: 'potber.de',
      API_URL: 'https://api.potber.de',
      AUTH_ISSUER_URL: 'https://auth.potber.de',
      MEME_HOST_URL: 'https://potber.de',
    };
