apiVersion: v1
kind: ConfigMap
metadata:
  name: potber-client-production
  namespace: potber
data:
  injected-config.js: |
    window.APP = {
      HOSTNAME: 'test.potber.de',
      API_URL: 'https://test-api.potber.de',
      AUTH_ISSUER_URL: 'https://test-auth.potber.de',
      MEME_HOST_URL: 'https://test.potber.de',
    };
