---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: potber-client-production
  namespace: potber
spec:
  imageRepositoryRef:
    name: potber-api
  filterTags:
    pattern: 'v*'
  policy:
    semver:
      range: '^1.0.0'