---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: potber-client-production
  namespace: potber
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - "*.spuxx.dev"
      secretName: spuxx.dev
  rules:
    - host: potber.spuxx.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: potber-client-production
                port:
                  number: 8080