---
apiVersion: v1
kind: Service
metadata:
  name: potber-client-production
  namespace: potber
spec:
  selector:
    app: potber-client-production
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
