apiVersion: v1
kind: Secret
metadata:
    name: mailu
    namespace: mailu
stringData:
    secretKey: ENC[AES256_GCM,data:zRTRtp5tTfuOU1ODvrZ7hE/Yf5MCr+XjOomcoYzY,iv:7CXLCWG6+vSskz1hotyp4u9ONqsjSmoYL+Q4LljK5MY=,tag:HWaju1HV3GiaR7C3nKsd1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-08T18:27:31Z"
    mac: ENC[AES256_GCM,data:kx1YGwTg6pGhJQE1dhsYCH+yFUua+SBhbwnFx4wCJZo/r+AbvGodgvCLGdu76aJXH/Hs1YTvUC9Yx/1eXImbU85VAR7cjfwE38gy5h2YMo56t+xaQ/XQGlokKG7aHVfBl6L91PNWR42epihdzGHMDs8+B3K1F4C2NnrvGRr/uFU=,iv:cVOw6XjGEgCu9TB26xuBgi+6v4SbbGGgeyW203UkS7k=,tag:2+qzonGlmJmCwjmTAk4rCg==,type:str]
    pgp:
        - created_at: "2023-07-08T18:27:30Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA77Feg6CYGihAQv/bLBchNzMYriGHtY3usQwrHkhaSVgaFQAgGMSEnyJ0Ra1
            /7sly/qKddNVJ2AAqg3nG/g+dRnKyJMKuDBMSjCBIr1o0vFwuak7QoKprF0wK4JY
            8Ao1pIpp0mJnM1Boi5WTvEucVmwWTZDenADI8WD2B0X1yN2AMo3CfaWdiT0w642i
            tDLucW7InM7g85ooCRyPPnyjeOJc40L2UA+Pvm/dMW+3k9QPqtaDUGv+iwSMK3yZ
            HCjuBXaCSWIQjLK+shZzGkbp9AV65DoAJCG50lHmAl5deeiA5CLn7kc+aPClpDUN
            B9cTbhwPjZfeqEjT3HjORHvLR8Ui8PMT2wQ43jymMk4z/gCnqoQTl7HWYDYhKpqN
            2NXB4/7bHbCYjVuRf9wWLgfTKIe/VIj+uMkOxuNuSn+EPhOs1NsHmvuSQzFNtSh7
            U65aGG63sdZtn0U9ZgAiPc3j6Hf0QMMMlWJpZ+4A+C3yJDbclcSLzdc+lTTZ1JUm
            BiccnGT8Y83etb6qKorJ0l4Bgsg5lOfhXqhGh6Pyr4Lq7/Mr8dNPhNgGw8w/yfm7
            oyBtkQBRBTxYolrutU7gebAQADFMwjPsNgCLEkxULt5svWj9pWnKF0WI39jOIolg
            SVAfPgbMyEC4iNpMeR2M
            =kcpm
            -----END PGP MESSAGE-----
          fp: 9E95B247726314CE9C9B773CCDED10EFD2585E50
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
