---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: actualbudget
  labels:
    type: local
spec:
  storageClassName: host-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/actualbudget
    type: DirectoryOrCreate
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: actualbudget
    namespace: storage
  capacity:
    storage: 10Gi
