apiVersion: v1
kind: PersistentVolume
metadata:
  name: ark-se
  labels:
    type: local
spec:
  storageClassName: host-storage
  type: hostPath
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: ark-se
    namespace: game-servers
  capacity:
    storage: 30Gi
