---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: firefly
  labels:
    type: local
spec:
  storageClassName: host-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/firefly
    type: DirectoryOrCreate
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: firefly
    namespace: storage
  capacity:
    storage: 10Gi
