---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring
  labels:
    type: local
spec:
  storageClassName: host-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/monitoring
    type: DirectoryOrCreate
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: monitoring
    namespace: storage
  capacity:
    storage: 10Gi
