---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: host-storage
  namespace: storage
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
parameters:
  pvDir: /opt/kube
volumeBindingMode: WaitForFirstConsumer
