apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  namespace: database
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-storage
  resources:
    requests:
      storage: 25Gi
