---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-dynamic
  namespace: database
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-storage
  resources:
    requests:
      storage: 25Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-static
  namespace: database
spec:
  capacity:
    storage: 25Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-storage
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '2'
      staleReplicaTimeout: '2880'
    volumeHandle: 'pvc-97c4b918-b699-432b-8456-16577fe4046e'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-static
  namespace: database
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-storage
  volumeName: mariadb-static
  resources:
    requests:
      storage: 25Gi
