---
# Flux system
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

---
# Apps
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-apps
  namespace: flux-system
spec:
  interval: 3m
  path: ./clusters/jupiter/apps/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
