---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: paperless-ngx
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      securityContext:
        fsGroup: 9999
      containers:
      - name: redis
        image: docker.io/library/redis:7
        ports:
        - containerPort: 6379
        securityContext:
          runAsNonRoot: true
          runAsUser: 9999
        volumeMounts:
        - name: redis
          mountPath: /data
      volumes:
      - name: redis
        persistentVolumeClaim:
          claimName: redis-dynamic
