---
# Production environment
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: lets-encrypt
spec:
  acme:
    email: leopoldhock@outlook.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          webhook:
            # See https://github.com/aellwein/cert-manager-webhook-netcup
            groupName: com.netcup.webhook
            solverName: netcup
            config:
              secretRef: netcup-secret
              secretNamespace: cert-manager
---
# Test environment
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: lets-encrypt
spec:
  acme:
    email: leopoldhock@outlook.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          webhook:
            # See https://github.com/aellwein/cert-manager-webhook-netcup
            groupName: com.netcup.webhook
            solverName: netcup
            config:
              secretRef: netcup-secret
              secretNamespace: cert-manager
